// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/spf13/viper"
	"github.com/varluffy/rich"
	"github.com/varluffy/rich/example/internal/domain"
	"github.com/varluffy/rich/example/internal/server/repo"
	"github.com/varluffy/rich/example/internal/server/service"
)

// Injectors from wire.go:

func newApp(conf *viper.Viper) (*rich.App, func(), error) {
	logger := initLogger(conf)
	db, cleanup, err := initMysql(conf, logger)
	if err != nil {
		return nil, nil, err
	}
	iArticleRepo := repo.NewArticleRepo(db)
	articleUseCase := domain.NewArticleUsecase(iArticleRepo)
	article := service.NewArticleService(articleUseCase)
	mainServices := &services{
		article: article,
	}
	server, err := initHttpServer(conf, logger, mainServices)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := initApp(logger, server)
	return app, func() {
		cleanup()
	}, nil
}
